%YAML 1.2
# tracker application configuration file
---
configVersion: 0.1

Application:
    name: tracker
    version: 12

ClientManager:
    maximumClientNumber: 10

PositionAcquirer:
    device: /dev/ttySAC1
    protocol: ???

Clients:
    - 
      type: console
      role:
          - monitor
          - commander

    - 
      type: push button
      role:
          - commander
          - position handler
          - monitor
      remote:
          ip: 123.124.125.16
          port: 1234
          host: www.eee.ccc
...
