%YAML 1.2
# tracker application configuration file
---
ConfigVersion: 0.1

Application:
    Name: tracker
    Version: 12

ClientManager:
    maximumClientNumber: 10
    minimumClientNumber: 1

Clients:
    - 
      type: console
      capabilities:
          - monitor
          - commander

    - 
      type: push button
      capabilities:
          - commander
          - position handler
          - monitor
      remote:
          ip: 123.124.125.16
          port: 1234
          host: www.eee.ccc
...
